services:
  nginx-frontend:
    build: ./vue-mpa
    container_name: warframe-tracker-frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./vue-mpa/nginx/ngnix.conf:/etc/nginx/nginx.conf
      - ./vue-mpa/nginx/nginx.conf.d:/etc/nginx/conf.d
      - ./https-setup:/etc/nginx/certs
    restart: unless-stopped

  backend:
    build:
      context: ./rest-api
      dockerfile: Dockerfile
    container_name: warframe-tracker-backend
    ports:
      - "5224:8080"
    environment:
      - DB_HOST=postgres
  
    env_file:
      - ./.env

  postgres:
    image: postgres:16.10-bookworm
    container_name: warframe-tracker-postgres
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: unless-stopped


  imgproxy:
    image: ghcr.io/imgproxy/imgproxy:latest
    container_name: imgproxy
    restart: unless-stopped

    environment:
      - IMGPROXY_CACHE_CONTROL_PASSTHROUGH=true
    
    volumes:
      - ./imgcache:/imgcache