ALTER TABLE player ADD COLUMN IF NOT EXISTS duviri_skills INT NOT NULL DEFAULT 0;
ALTER TABLE player ADD COLUMN IF NOT EXISTS railjack_skills INT NOT NULL DEFAULT 0;
ALTER TABLE player ADD COLUMN IF NOT EXISTS total_mastery_xp INT NOT NULL DEFAULT 0;