services:
  imgproxy:
    image: ghcr.io/imgproxy/imgproxy:latest
    container_name: imgproxy
    restart: unless-stopped
    ports:
      - "20080:8080"

    environment:
      - IMGPROXY_CACHE_CONTROL_PASSTHROUGH=true
    
    volumes:
      - ./imgcache:/imgcache
    
    networks:
      - app-network

networks:
  app-network:
    external: true