// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using rest_api.Data;

#nullable disable

namespace rest_api.Migrations
{
    [DbContext(typeof(WarframeTrackerDbContext))]
    [Migration("20260108183615_AddTriggersAndIndexes")]
    partial class AddTriggersAndIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "invitation_status", new[] { "pending", "accepted", "declined", "canceled" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("player_clan", b =>
                {
                    b.Property<int>("clan_id")
                        .HasColumnType("integer");

                    b.Property<int>("player_id")
                        .HasColumnType("integer");

                    b.HasKey("clan_id", "player_id")
                        .HasName("player_clan_pkey");

                    b.HasIndex("player_id");

                    b.ToTable("player_clan", (string)null);
                });

            modelBuilder.Entity("rest_api.Models.Clan", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("leader_id")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("id")
                        .HasName("clan_pkey");

                    b.HasIndex("leader_id");

                    b.HasIndex(new[] { "name" }, "clan_name_key")
                        .IsUnique();

                    b.ToTable("clan", (string)null);
                });

            modelBuilder.Entity("rest_api.Models.Clan_invitation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("clan_id")
                        .HasColumnType("integer");

                    b.Property<int>("player_id")
                        .HasColumnType("integer");

                    b.Property<string>("status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("invitation_status");

                    b.HasKey("id")
                        .HasName("clan_invitation_pkey");

                    b.HasIndex("clan_id");

                    b.HasIndex("player_id");

                    b.ToTable("clan_invitation", (string)null);
                });

            modelBuilder.Entity("rest_api.Models.Item", b =>
                {
                    b.Property<string>("unique_name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("item_class")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("xp_required")
                        .HasColumnType("integer");

                    b.HasKey("unique_name")
                        .HasName("item_pkey");

                    b.ToTable("item", (string)null);
                });

            modelBuilder.Entity("rest_api.Models.Mission", b =>
                {
                    b.Property<string>("UniqueName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("unique_name");

                    b.Property<int>("MasteryXp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("mastery_xp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("Planet")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("planet");

                    b.Property<string>("Type")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("type");

                    b.HasKey("UniqueName")
                        .HasName("missions_pkey");

                    b.ToTable("missions", (string)null);
                });

            modelBuilder.Entity("rest_api.Models.MissionCompletion", b =>
                {
                    b.Property<string>("UniqueName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("unique_name");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.Property<int>("CompletionCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("completes");

                    b.Property<bool>("SPComplete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("sp_complete");

                    b.HasKey("UniqueName", "PlayerId")
                        .HasName("player_mission_completion_pkey");

                    b.HasIndex("PlayerId");

                    b.ToTable("player_mission_completion", (string)null);
                });

            modelBuilder.Entity("rest_api.Models.Player", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("TotalMasteryXp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_mastery_xp");

                    b.Property<int>("duviri_skills")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("mastery_rank")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("railjack_skills")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("id")
                        .HasName("player_pkey");

                    b.HasIndex(new[] { "username" }, "player_username_key")
                        .IsUnique();

                    b.ToTable("player", (string)null);
                });

            modelBuilder.Entity("rest_api.Models.Player_item", b =>
                {
                    b.Property<string>("unique_name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("player_id")
                        .HasColumnType("integer");

                    b.Property<int>("item_count")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("unique_name", "player_id")
                        .HasName("player_items_pkey");

                    b.HasIndex("player_id");

                    b.ToTable("player_items");
                });

            modelBuilder.Entity("rest_api.Models.Player_items_mastery", b =>
                {
                    b.Property<string>("unique_name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("player_id")
                        .HasColumnType("integer");

                    b.Property<int>("xp_gained")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("unique_name", "player_id")
                        .HasName("player_items_mastery_pkey");

                    b.HasIndex("player_id");

                    b.ToTable("player_items_mastery", (string)null);
                });

            modelBuilder.Entity("rest_api.Models.Recipe", b =>
                {
                    b.Property<string>("unique_name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("result_item")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("unique_name")
                        .HasName("recipe_pkey");

                    b.HasIndex("result_item");

                    b.ToTable("recipe", (string)null);
                });

            modelBuilder.Entity("rest_api.Models.Recipe_ingredient", b =>
                {
                    b.Property<string>("recipe_name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("item_ingredient")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("ingredient_count")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("recipe_name", "item_ingredient")
                        .HasName("recipe_ingredients_pkey");

                    b.HasIndex("item_ingredient");

                    b.ToTable("recipe_ingredients");
                });

            modelBuilder.Entity("rest_api.Models.RefreshToken", b =>
                {
                    b.Property<string>("Token")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("token");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expires");

                    b.Property<DateTime>("Issued")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("issued");

                    b.Property<string>("IssuedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("issued_by_ip");

                    b.Property<bool>("Revoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("revoked");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Token")
                        .HasName("refresh_token_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("refresh_token", (string)null);
                });

            modelBuilder.Entity("rest_api.Models.Registered_user", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.PrimitiveCollection<List<string>>("Roles")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("roles");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("player_id")
                        .HasColumnType("integer");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("id")
                        .HasName("registered_user_pkey");

                    b.HasIndex("player_id");

                    b.HasIndex(new[] { "username" }, "registered_user_username_key")
                        .IsUnique();

                    b.ToTable("registered_user", (string)null);
                });

            modelBuilder.Entity("player_clan", b =>
                {
                    b.HasOne("rest_api.Models.Clan", null)
                        .WithMany()
                        .HasForeignKey("clan_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("player_clan_clan_id_fkey");

                    b.HasOne("rest_api.Models.Player", null)
                        .WithMany()
                        .HasForeignKey("player_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("player_clan_player_id_fkey");
                });

            modelBuilder.Entity("rest_api.Models.Clan", b =>
                {
                    b.HasOne("rest_api.Models.Player", "leader")
                        .WithMany("clansLeading")
                        .HasForeignKey("leader_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("clan_leader_id_fkey");

                    b.Navigation("leader");
                });

            modelBuilder.Entity("rest_api.Models.Clan_invitation", b =>
                {
                    b.HasOne("rest_api.Models.Clan", "clan")
                        .WithMany("clan_invitations")
                        .HasForeignKey("clan_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("clan_invitation_clan_id_fkey");

                    b.HasOne("rest_api.Models.Player", "player")
                        .WithMany("clan_invitations")
                        .HasForeignKey("player_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("clan_invitation_player_id_fkey");

                    b.Navigation("clan");

                    b.Navigation("player");
                });

            modelBuilder.Entity("rest_api.Models.MissionCompletion", b =>
                {
                    b.HasOne("rest_api.Models.Player", "Player")
                        .WithMany("MissionsCompleted")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("player_mission_completion_player_id_fkey");

                    b.HasOne("rest_api.Models.Mission", "Mission")
                        .WithMany("MissionCompletions")
                        .HasForeignKey("UniqueName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("player_mission_completion_unique_name_fkey");

                    b.Navigation("Mission");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("rest_api.Models.Player_item", b =>
                {
                    b.HasOne("rest_api.Models.Player", "player")
                        .WithMany("player_items")
                        .HasForeignKey("player_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("player_items_player_id_fkey");

                    b.HasOne("rest_api.Models.Item", "unique_nameNavigation")
                        .WithMany("player_items")
                        .HasForeignKey("unique_name")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("player_items_unique_name_fkey");

                    b.Navigation("player");

                    b.Navigation("unique_nameNavigation");
                });

            modelBuilder.Entity("rest_api.Models.Player_items_mastery", b =>
                {
                    b.HasOne("rest_api.Models.Player", "player")
                        .WithMany("player_items_masteries")
                        .HasForeignKey("player_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("player_items_mastery_player_id_fkey");

                    b.HasOne("rest_api.Models.Item", "item")
                        .WithMany("player_items_masteries")
                        .HasForeignKey("unique_name")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("player_items_mastery_unique_name_fkey");

                    b.Navigation("item");

                    b.Navigation("player");
                });

            modelBuilder.Entity("rest_api.Models.Recipe", b =>
                {
                    b.HasOne("rest_api.Models.Item", "result_itemNavigation")
                        .WithMany("reciperesult_itemNavigations")
                        .HasForeignKey("result_item")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("recipe_result_item_fkey");

                    b.HasOne("rest_api.Models.Item", "unique_nameNavigation")
                        .WithOne("recipeunique_nameNavigation")
                        .HasForeignKey("rest_api.Models.Recipe", "unique_name")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("recipe_unique_name_fkey");

                    b.Navigation("result_itemNavigation");

                    b.Navigation("unique_nameNavigation");
                });

            modelBuilder.Entity("rest_api.Models.Recipe_ingredient", b =>
                {
                    b.HasOne("rest_api.Models.Item", "item_ingredientNavigation")
                        .WithMany("recipe_ingredients")
                        .HasForeignKey("item_ingredient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("recipe_ingredients_item_ingredient_fkey");

                    b.HasOne("rest_api.Models.Recipe", "recipe_nameNavigation")
                        .WithMany("recipe_ingredients")
                        .HasForeignKey("recipe_name")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("recipe_ingredients_recipe_name_fkey");

                    b.Navigation("item_ingredientNavigation");

                    b.Navigation("recipe_nameNavigation");
                });

            modelBuilder.Entity("rest_api.Models.RefreshToken", b =>
                {
                    b.HasOne("rest_api.Models.Registered_user", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("refresh_token_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("rest_api.Models.Registered_user", b =>
                {
                    b.HasOne("rest_api.Models.Player", "player")
                        .WithMany("registered_users")
                        .HasForeignKey("player_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("registered_user_player_id_fkey");

                    b.Navigation("player");
                });

            modelBuilder.Entity("rest_api.Models.Clan", b =>
                {
                    b.Navigation("clan_invitations");
                });

            modelBuilder.Entity("rest_api.Models.Item", b =>
                {
                    b.Navigation("player_items");

                    b.Navigation("player_items_masteries");

                    b.Navigation("recipe_ingredients");

                    b.Navigation("reciperesult_itemNavigations");

                    b.Navigation("recipeunique_nameNavigation");
                });

            modelBuilder.Entity("rest_api.Models.Mission", b =>
                {
                    b.Navigation("MissionCompletions");
                });

            modelBuilder.Entity("rest_api.Models.Player", b =>
                {
                    b.Navigation("MissionsCompleted");

                    b.Navigation("clan_invitations");

                    b.Navigation("clansLeading");

                    b.Navigation("player_items");

                    b.Navigation("player_items_masteries");

                    b.Navigation("registered_users");
                });

            modelBuilder.Entity("rest_api.Models.Recipe", b =>
                {
                    b.Navigation("recipe_ingredients");
                });

            modelBuilder.Entity("rest_api.Models.Registered_user", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
